### PR TITLE
Fix atom deprecations

### PR DESCRIPTION
**Pull request by jbergstroem**
..because that triangle annoys me :)

### CODE REVIEW

**Comment by jbergstroem** [comment]
ping?

**Comment by jbergstroem** [comment]
Would you perhaps accept me to co-maintain this?

**Comment by mbullington** [comment]
Thank you for your pull request.

Sorry about the long wait, I've really been meaning to merge this. I've also added you as a contributor, you now have commit access to this repository.

**Comment by jbergstroem** [comment]
Thanks for merging and trusting me with `+w`.

**Pull request merged**
