### PR TITLE
ThemePackage.getStylesheetsPath is deprecated

### PR DESCRIPTION
**Pull request by jbergstroem**
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `quantum-syntax` package
```
ThemePackage.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app/src/package.js:448:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:492:35)
```

### CODE REVIEW

**Comment by jbergstroem** [comment]
Do we perhaps want to bump the atom version requirement for this?

**Comment by mbullington** [comment]
Sure. I'll work on merging these later today. Thanks again for helping out with maintaining the Quantum themes.

**Comment by jbergstroem** [comment]
Fyi, I'm looking at bringing it up to date for the `--one` flag shortly. The atom dark theme seems to be good inspriation.

**Comment by Waregalias** [comment]
08-07-2015 : 

"quantum-syntax (2 deprecations)
Store package style sheets in the styles/ directory instead of stylesheets/ in the quantum-syntax package

ThemePackage.getStylesheetsPath - C:\Users\Smezhoud\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:465:9
ThemePackage.getStylesheetPaths - C:\Users\Smezhoud\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:476:32
ThemePackage.loadStylesheets - C:\Users\Smezhoud\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:458:38
<unknown> - C:\Users\Smezhoud\AppData\Local\atom\app-1.0.3\resources\app.asar\src\theme-package.js:47:19
ThemePackage.measure - C:\Users\Smezhoud\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:167:15
ThemePackage.activate - C:\Users\Smezhoud\AppData\Local\atom\app-1.0.3\resources\app.asar\src\theme-package.js:43:12

ThemePackage.getStylesheetsPath - C:\Users\Smezhoud\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:465:9
<unknown> - C:\Users\Smezhoud\AppData\Local\atom\app-1.0.3\resources\app.asar\src\theme-manager.js:434:35
ThemeManager.getImportPaths - C:\Users\Smezhoud\AppData\Local\atom\app-1.0.3\resources\app.asar\src\theme-manager.js:438:11
ThemeManager.refreshLessCache - C:\Users\Smezhoud\AppData\Local\atom\app-1.0.3\resources\app.asar\src\theme-manager.js:421:75
<unknown> - C:\Users\Smezhoud\AppData\Local\atom\app-1.0.3\resources\app.asar\src\theme-manager.js:368:19
_fulfilled - C:\Users\Smezhoud\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\q\q.js:794:54"

**Pull request merged**
